services:
  nginx-webdav:
    image: linuxserver/nginx
    container_name: nginx-webdav
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBDAV_USER=user
      - WEBDAV_PASSWORD=pwd
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8080:80
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/config/init.sh"]
