services:
  easydav:
    image: xieyanbo/easydav
    container_name: easydav
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBDAV_USER=user
      - WEBDAV_PASSWORD=pwd
    volumes:
      - ./data:/data
    ports:
      - 8080:80
    restart: unless-stopped
